### ISSUE TITLE
Native Compatibility with Gnome 48

### ISSUE THREAD

**Issue by alghostzx** [Vishram1123/gjs-osk#102]
The version offered by the extension store only goes to Gnome 47, is there plans to update to Gnome 48?

Thanks for the extension, by far the best OSK for gnome.

**Comment by Vishram1123** [comment]
Will do once my semester closes out; been kinda stressful with finals approaching sorry

**Comment by alghostzx** [comment]
no please, don't apologize, I'm sorry for imposing, you do it whenever you can! thank you so much!

**Comment by lacksfish** [comment]
Isn't this fixed by https://github.com/Vishram1123/gjs-osk/pull/97 ?

**Comment by alghostzx** [comment]
https://extensions.gnome.org/extension/5949/gjs-osk/ still doesn't show as gnome 48 compatible.
