### ISSUE TITLE
special keys have no icons

### ISSUE THREAD

**Issue by MariahWest01** [Vishram1123/gjs-osk#49]
im on debian 12 and the extension autoupdated. the icons for the special keys are gone but still work \
![Screenshot from 2024-07-03 12-54-00](https://github.com/Vishram1123/gjs-osk/assets/133059536/1dd895dc-9534-4bf9-b9d5-c45a00b74df3)

**Comment by Vishram1123** [comment]
What are your settings? Are there any error messages in Extension

**Comment by MariahWest01** [comment]
there was some error about missing toggles. i hopped to fedora and its fine. can you add more keys by chance? like home and stuff. i use it to type on my tablet exclusively

**Comment by oyvindknustad** [comment]
This is the error message I get for the same issue:

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/6556a083-ee11-4421-96ef-04048823b4e4)

And this is my settings. I haven't changed anything:

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/bb1bc60f-ebe1-4c41-b9bb-547472a3a932)
![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/b67baef1-f4a5-4828-8cc9-017e0fdd623e)

**Comment by Vishram1123** [comment]
Seems that this was specific to gnome 43, as a patch was released in GNOME 44 that changed the name of the property holding the title of a quick menu toggle. I fixed this, and sent this to the review team. For now, you can download the `pre-45` archive from the latest release and install using the instructions there.

**Comment by oyvindknustad** [comment]
The issue is still there, but I'm getting a different error message:

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/f08aac63-f8db-4219-802e-e21530668a36)

**Comment by Vishram1123** [comment]
I will get back to this as soon as possible

**Comment by MariahWest01** [comment]
> > there was some error about missing toggles. i hopped to fedora and its fine. can you add more keys by chance? like home and stuff. i use it to type on my tablet exclusively
> 
> What do you mean by this? As in, like function row home, pgup, pgdown, and end?

yes. i would like all the keys on a standard qwerty keyboard. its hell trying to use terminal without them

**Comment by oyvindknustad** [comment]
I don't know what happened, but the keyboard works perfectly now.  I guess a restart of the computer did it good

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/2313ba96-651c-47cb-b9ab-6effc39660d0)

**Comment by Vishram1123** [comment]
Ah I updated the keyboard to fix an undefined variable, nice to see it works!

**Comment by Vishram1123** [comment]
> there was some error about missing toggles. i hopped to fedora and its fine. can you add more keys by chance? like home and stuff. i use it to type on my tablet exclusively

#54 will continue this.

**Comment by MariahWest01** [comment]
this might be off topic but is there a way to use this keyboard on other des like kde?

**Comment by Vishram1123** [comment]
No, this keyboard is specific to GNOME only, sorry

**Comment by Vishram1123** [comment]
Sorry for the confusing mega-commit 1fad5fd, but different layouts (that can be selected through settings, including a full size 105 key, and a tenkeyless layout) have been added. Will send to the extensions team once these changes have been backported to pre-45

**Comment by MariahWest01** [comment]
thats awesome. thank uuu
